language: objective-c
osx_image: xcode10.2
env:
  - PROJECT=Valet.xcodeproj
  - IOS_FRAMEWORK_SCHEME="Valet iOS"
  - MACOS_FRAMEWORK_SCHEME="Valet macOS"
  - TVOS_FRAMEWORK_SCHEME="Valet tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="Valet watchOS"
matrix:
  - SCHEME="$IOS_FRAMEWORK_SCHEME" DESTINATION="OS=12.2,name=iPhone XS" ACTION="build test"
  - SCHEME="$TVOS_FRAMEWORK_SCHEME" DESTINATION="OS=12.2,name=Apple TV 4K" ACTION="build test"
  - SCHEME="$WATCHOS_FRAMEWORK_SCHEME" DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm" ACTION="build test"
  - SCHEME="$MACOS_FRAMEWORK_SCHEME" DESTINATION="platform=OS X" ACTION="build"
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
before_script:
  - bundle exec pod lib lint --verbose --fail-fast
  - carthage build --verbose --no-skip-current
script:
  - xcodebuild -project Valet.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug -PBXBuildsContinueAfterErrors=0 $ACTION
